Feature/update lib xud
xmos/fwk_rtos pull request #133
Opened 2023-03-24 18:40 UTC by jcarrier-xmos

Updated lib_xud and re-established support in the rtos usb component.

2023-03-27 18:11 UTC, xmos-jmccarthy requested changes
Looks good.

Do we have feature requests of lib_xud to resolve the last few open duplicated code that we have here?  We will need all functionality inside of lib_xud once we fully convert to polyrepo, otherwise there will be different lib_xud APIs based on how you got the code, despite them pointing to the same tagged release.

Requesting evaluating the bool to int8_t change for setup packet flagging, just to make sure the uint8_t isn't adding too many extra cycles.  3 more bytes will be well worth the cost of potential timing issues.

2023-03-27 18:11 UTC, xmos-jmccarthy commented on modules/drivers/usb/src/xud_xfer_data.S
Is there a PR on lib_xud for this change, or a git issue to add this functionality to the lib_xud API?

2023-03-27 18:11 UTC, xmos-jmccarthy commented on modules/drivers/usb/src/xud_xfer_data.h
Is there a PR on lib_xud for this change, or a git issue to add this functionality to the lib_xud API?

2023-03-27 18:11 UTC, xmos-jmccarthy commented on modules/sw_services/usb/portable/dcd_xcore.c
We may want to check the disassembly just to make sure changing from a bool to a uint8_t doesn't add too many cycles.  Non word size access are much slower, and getting the setup packet and ZLP buffers ASAP is important to avoid timing related problems.

2023-03-27 18:47 UTC, jcarrier-xmos commented on modules/sw_services/usb/portable/dcd_xcore.c
I only swapped this out to avoid adding a #include somewhere else for stdbool.h when I was testing something out, but after some cleanup that change is not even relevant anymore.

I would be interested to verify this anyways. I would be a bit surprised if there is any difference since we have LD8U/ST8U instructions. This would certainly be a take a hit on a 16-bit char platform.

2023-03-29 14:21 UTC, jcarrier-xmos commented on modules/sw_services/usb/portable/dcd_xcore.c
I reverted back to bool (and updated rtos_usb_endpoint_transfer_start's new argument to match).

2023-04-11 19:02 UTC, xmos-jmccarthy requested changes

2023-04-12 13:58 UTC, merged