Prepare release v3.2.0
xmos/fwk_rtos pull request #241
Opened 2024-07-26 16:22 UTC by ACascarino

* FIXED: Windows host issue with pre-2013 Visual Studio Compiler and stdbool.h.
  * UPDATED: libusb host drivers for Windows to v1.0.27. The device must now use WinUSB drivers on Windows.
  * UPDATED: To tinyusb_src commit c61f5f4, it includes official support for USB test mode.
  * FIXED: Adopted common format in error printouts of device control host drivers.
TODO: Update changelog version

2024-07-29 17:06 UTC, mbanth requested changes

2024-07-30 11:00 UTC, ACascarino commented on CHANGELOG.rst
> +UNRELEASED
Resolved in https://github.com/xmos/fwk_rtos/pull/241/commits/1133566d2215fd285ffe1c9114bdb3e4417d85b1

2024-07-30 11:01 UTC, ACascarino commented on Jenkinsfile
>  @Library('xmos_jenkins_shared_library@v0.28.0') _
As agreed in backlog grooming, will also bump Tools to 15.3.0

2024-07-30 11:03 UTC, ACascarino commented on modules/sw_services/device_control/host/device_access_usb.c
> +#define PRINT_ERROR(...)   fprintf(stderr, "Error  : " __VA_ARGS__)
Agreed. This definition appears to only be used in the device_control sw_service so will put it in a common area for those. Another declaration for it exists in argtable.c but that's a different definition so will leave that alone.

2024-08-02 16:22 UTC, mbanth approved these changes
I have made a few comments.  They all mention optional changes, nothing that I think is required as part of the release.

2024-08-02 16:24 UTC, ACascarino commented
@mbanth thank you for your comments - I'd like to raise stories in LSM to address these in a future release

2024-08-02 16:24 UTC, merged